services:
  # TODO: enable if needed, I already have existing postgres setup
  # postgres_db:
  #   image: postgres:16
  #   container_name: py_ai_translator_postgres
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #     - POSTGRES_HOST=${DB_HOST}
  #     - POSTGRES_PORT=${DB_PORT}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  app:
    container_name: py_ai_translator
    build: .
    image: dhruvahuja/py_ai_translator
    ports:
      - 8002:8000
    env_file:
      - .env.deploy
    networks:
      - app-network
    # mounts the current directory (.) to the /app directory in the container,
    # so changes made to the code will be reflected inside the container
    # volumes:
    #   - .:/app

networks:
  app-network:
    external: true
