"""make url unique

Revision ID: e80071a53c12
Revises: 0312e83ac1b0
Create Date: 2025-03-30 02:03:57.082166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80071a53c12'
down_revision: Union[str, None] = '0312e83ac1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crawled_data_url', table_name='crawled_data')
    op.create_index(op.f('ix_crawled_data_url'), 'crawled_data', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawled_data_url'), table_name='crawled_data')
    op.create_index('ix_crawled_data_url', 'crawled_data', ['url'], unique=False)
    # ### end Alembic commands ###
